### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by port19x** [Mohmad-Naser-alnakeshbandi/Mensa-App#1]
Can you package this as an android apk?
Such an apk would best be added as an asset to a github release.
You could then add it to the google play store or fdroid (if you choose to license this under a free license)

**Comment by Mohmad-Naser-alnakeshbandi** [comment]
I already have the APK installed on my phone, the problem is I can not publish the App on GitHub or even on Google play, because I used web scrapping to get the information and i am not sure if I am allowed to do it. The entire problem can be solved, if the DHBW will provides an API

**Comment by port19x** [comment]
> 

Web scraping = web browser.
Legally speaking your app is a special purpose web browser

**Comment by Mohmad-Naser-alnakeshbandi** [comment]
Pls use the following commands to install the app

npm install --global eas-cli
eas submit --platform android --url https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40mohmamadnaser/Mensa-App-20f862f60e704045a8074715b22df7fc-signed.apk
