### ISSUE TITLE
Darkmode?

### ISSUE THREAD

**Issue by port19x** [Mohmad-Naser-alnakeshbandi/Mensa-App#2]
Like solid black dark mode for oled mobile phones.
I'd unironically use this app

**Comment by port19x** [comment]
[csicar/MensaPlan](https://github.com/csicar/MensaPlan) hat keinen Darkmode und der [openmensa](https://openmensa.org/c/33) parser ist kaputt

**Comment by Mohmad-Naser-alnakeshbandi** [comment]
I am working on the Dark Mode, it will be an option + Font resizer

**Comment by Mohmad-Naser-alnakeshbandi** [comment]
pls check version 2.0 to check the all new features
